network:
    version: 2
    renderer: networkd
    ethernets:
        eth0:
            addresses:
                - 192.168.1.5/24
            nameservers:
                addresses: [1.1.1.1, 1.0.0.1]
            routes:
                - to: default
                  via: 192.168.1.1
    vlans:
        vlan10:
            id: 10
            link: eth0
            addresses:
                - 10.0.10.5/23
